[workspace]
members = [
    "crates/asm",
    "crates/common",
    "crates/hack",
    "crates/hasm",
    "crates/hdisasm",
    "crates/jack",
    "crates/jack-analyzer",
    "crates/vm",
    "crates/vmtrans"
]
