[package]
name = "vmtrans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
common = { path = "../common" }
vm = { path = "../vm" }
