[package]
name = "hdisasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asm = { path = "../asm" }
color-eyre = "0.5.11"
tempfile = "3.2.0"
