[package]
name = "jack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
parse-display = "0.5.3"
thiserror = "1.0.30"
