[package]
name = "hasm"
version = "0.1.0"
edition = "2021"
description = "Hack assembler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asm = { path = "../asm" }
common = { path = "../common" }
color-eyre = "0.5.11"

